// Writes src/brand-active/* as re-exports of the brand chosen by $BRAND.
// Run before dev/build/typecheck: `BRAND=quaeris node scripts/select-brand.mjs`
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const VALID = ["veris", "quaeris"];
const brand = process.env.BRAND ?? "veris";
if (!VALID.includes(brand)) {
  console.error(`Unknown BRAND "${brand}". Valid brands: ${VALID.join(", ")}`);
  process.exit(1);
}

const here = path.dirname(fileURLToPath(import.meta.url));
const dir = path.join(here, "..", "src", "brand-active");
mkdirSync(dir, { recursive: true });

const banner = "GENERATED by scripts/select-brand.mjs — do not edit";
writeFileSync(path.join(dir, "config.ts"), `// ${banner}\nexport * from "../brands/${brand}/config";\n`);
writeFileSync(path.join(dir, "fonts.ts"), `// ${banner}\nexport * from "../brands/${brand}/fonts";\n`);
writeFileSync(path.join(dir, "tokens.css"), `/* ${banner} */\n@import "../brands/${brand}/tokens.css";\n`);
console.log(`brand-active → ${brand}`);
