// Writes src/brand-active/* as re-exports of the brand chosen by $BRAND.
// Run before dev/build/typecheck: `BRAND=quaeris node scripts/select-brand.mjs`
// NOTE: reads the shell env only (not .env.local). One brand per checkout at a
// time — concurrent dev servers would share brand-active/ and .next/.
import { mkdirSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const VALID = ["veris", "quaeris"];
const brand = process.env.BRAND ?? "veris";
if (!VALID.includes(brand)) {
  console.error(`Unknown BRAND "${brand}". Valid brands: ${VALID.join(", ")}`);
  process.exit(1);
}

const here = path.dirname(fileURLToPath(import.meta.url));
const dir = path.join(here, "..", "src", "brand-active");
mkdirSync(dir, { recursive: true });

const banner = "GENERATED by scripts/select-brand.mjs — do not edit";
writeFileSync(path.join(dir, "config.ts"), `// ${banner}\nexport * from "../brands/${brand}/config";\n`);
writeFileSync(path.join(dir, "fonts.ts"), `// ${banner}\nexport * from "../brands/${brand}/fonts";\n`);
writeFileSync(path.join(dir, "tokens.css"), `/* ${banner} */\n@import "../brands/${brand}/tokens.css";\n`);

// Pages barrel — scan src/brands/<brand>/pages/*.ts and re-export each, so per-page
// content modules need no hand-maintained barrel (conflict-free for parallel ports).
const pagesDir = path.join(here, "..", "src", "brands", brand, "pages");
let pageExports = "";
if (existsSync(pagesDir)) {
  const files = readdirSync(pagesDir)
    .filter((f) => f.endsWith(".ts") && f !== "index.ts")
    .sort();
  pageExports = files
    .map((f) => `export * from "../brands/${brand}/pages/${f.replace(/\.ts$/, "")}";`)
    .join("\n");
}
writeFileSync(
  path.join(dir, "pages.ts"),
  `// ${banner}\n${pageExports || "export {};"}\n`
);

console.log(`brand-active → ${brand}`);
